// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-Wu4_Cm3LjYBsBdQ9DfKuiZMoOLiGJk',
    appId: '1:901137107375:web:e820a3b717b616ad30875a',
    messagingSenderId: '901137107375',
    projectId: 'base-app-profesores',
    authDomain: 'base-app-profesores.firebaseapp.com',
    databaseURL: 'https://base-app-profesores-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'base-app-profesores.appspot.com',
    measurementId: 'G-19S9K954GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaltf6CC6cfGWebuVtAzktq7FdfgeG7LU',
    appId: '1:901137107375:android:6499f41715f7ae1730875a',
    messagingSenderId: '901137107375',
    projectId: 'base-app-profesores',
    databaseURL: 'https://base-app-profesores-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'base-app-profesores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA86vl-mCeicpwLzVE0-g3kWdxnjuRMC70',
    appId: '1:901137107375:ios:4d8830b82f9bf94030875a',
    messagingSenderId: '901137107375',
    projectId: 'base-app-profesores',
    databaseURL: 'https://base-app-profesores-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'base-app-profesores.appspot.com',
    iosBundleId: 'com.example.appProfesores',
  );
}
